#!/usr/bin/env python3

import subprocess
import json

public_dns = 'ec2-54-198-176-230.compute-1.amazonaws.com'
mlx_dir = '/Users/lewfish/projects/mlx/'
spot_path = '/Users/lewfish/.mlx/spot.json'

with open(spot_path, 'r') as spot_file:
    spot_dict = json.load(spot_file)
    public_dns = spot_dict['public_dns']

cmd = ['rsync', '-avzr', '--include=\"*\"', '--exclude=\"*\"',
       '--include=\"*.py$ *.yml$\"', mlx_dir,
       'ec2-user@{}:/home/ec2-user/mlx/'.format(public_dns)]
subprocess.run(cmd)