#!/usr/bin/env python3

import json
import subprocess
import sys

spot_path = '/Users/lewfish/.mlx/spot.json'

with open(spot_path, 'r') as spot_file:
    spot_dict = json.load(spot_file)
    public_dns = spot_dict['public_dns']

command = sys.argv[1]
docker_cmd = ('docker run --shm-size 16G --runtime=nvidia --rm -it '
              '-v /home/ec2-user/mlx/:/opt/src -v /home/ec2-user/data:/opt/data '
              '279682201306.dkr.ecr.us-east-1.amazonaws.com/raster-vision-gpu-lewfish:pytorch {}').format(command)
print(docker_cmd)

cmd = ['ssh', '-i', '~/.aws/lewfish-raster-vision.pem', '-t', 
       'ec2-user@{}'.format(public_dns), docker_cmd]
subprocess.run(cmd)
