model:
  type: "centernet"
  centernet:
    backbone_arch: "resnet18"
    nms: True
    max_pool_nms: True
    encoder:
      mode: 'rectangle'
      radius: 0
    loss:
      mode: "focal_bce"
      alpha: 2.0
      reg_scale: 1.0
    head:
      mode: "deep"
      num_blocks: 4
solver:
  lr: 1.25e-4
  num_epochs: 10
  sync_interval: 2
  batch_sz: 32
  overfit_num_steps: 400
  test_num_epochs: 2
  one_cycle: True
data:
  dataset: "pascal2007"
  img_sz: 224