model:
  type: "centernet"
  centernet:
    backbone_arch: "resnet18"
    body_arch: 'fcn'
    nms: True
    max_pool_nms: True
    encoder:
      mode: 'gaussian'
    loss:
      mode: "centernet"
      reg_scale: 0.1
      alpha: 2.0
      beta: 4.0
    head:
      mode: "deep"
      num_blocks: 8

solver:
  lr: 2.5e-4
  num_epochs: 10
  sync_interval: 2
  batch_sz: 32
  overfit_num_steps: 400
  test_num_epochs: 2
  one_cycle: True
data:
  dataset: "pascal2007"
  img_sz: 256
  train_aug:
    rgb_shift: True
    shift_scale_rotate: True
    hflip: True
  test_aug:
    hflip: False