model:
  type: "centernet"
  centernet:
    backbone_arch: "resnet18"
solver:
  lr: 1e-4
  num_epochs: 10
  sync_interval: 2
  batch_sz: 16
  overfit_num_epochs: 500
  overfit_sync_interval: 1000
  test_num_epochs: 1
data:
  dataset: "pascal2007"
  img_sz: 224